# Lua isn't a supported language; using fake-erlang, as per
# http://thejacklawson.com/2012/09/lua-testing-with-busted-and-travis-ci/
language: erlang

env: LUA="luajit"

before_install: git submodule update --init

script: make && make check
